### PR TITLE
Fixed error main.js:5 Uncaught TypeError: typedoc.Application is not a constructor

### PR DESCRIPTION
**Pull request by timocov**
Hi there,

this is fix for https://github.com/TypeStrong/typedoc/issues/343 issue.
Also I have compiled project with TypeScript 2.1.4.

### CODE REVIEW

**Comment by blakeembrey** [comment]
What's the change other than recompilation?

**Comment by timocov** [comment]
Added `/// <reference path="./typedoc/Application.ts" />` to `~bootstrap.ts`

**Comment by blakeembrey** [comment]
Why would that fix the referred issue? The issue you linked was a runtime issue.

**Comment by timocov** [comment]
I guess it happened after change system from `commonjs` to `amd`.
But in case of `amd` you need to set dependencies to your file. `~bootstrap.ts` doesn't have it and it has been executed the first (but there is no `Application` class yet)

**Comment by timocov** [comment]
Just look at [this code](https://github.com/TypeStrong/typedoc-default-themes/pull/29/files#diff-9a87419993af9a0764cad222c9f52c68L7). There is trying to create `Application` instance before it has been [declared](https://github.com/TypeStrong/typedoc-default-themes/pull/29/files#diff-9a87419993af9a0764cad222c9f52c68L11) (the link to the function with `Application` class implementation)

**Comment by blakeembrey** [comment]
That should have nothing to do with a reference though. You're pointing to runtime, whereas the reference doesn't change anything for runtime.

**Comment by timocov** [comment]
Without a reference the order of modules is the same as in master.

**Comment by blakeembrey** [comment]
Great, I see now. Thanks.

**Comment by timocov** [comment]
Thanks!

**Pull request merged**
