### PR TITLE
Fix sticky menu

### PR DESCRIPTION
**Pull request by BennyHinrichs**
Remove `MenuSticky.ts` and add CSS to make the sticky menu work. Fix for TypeStrong/typedoc/issues/985.

### CODE REVIEW

**Comment by Gerrit0** [comment]
This looks like a good change to me, but unfortunately it breaks if too many members are listed in the menu, I think it should be fixable if the overflow on the sticky container is set to `auto` and the max height is appropriately set.

**Comment by BennyHinrichs** [comment]
@Gerrit0 `position: sticky` on an element doesn't really work if a parent has `overflow` set to anything other than `visible` ([article](https://uxdesign.cc/position-stuck-96c9f55d9526)). Unless you're talking about `.tsd-navigation.secondary` and not `.menu-sticky-wrap`?

Oh, it also looks like I forgot to add `-webkit-` support.

Edit: I added `-webkit-sticky`. There's a big block of CSS in `.menu-sticky-wrap`.

Edit 2: I added `overflow: auto` and `max-height: calc(100vh - 1rem)` to `.secondary`. Maybe instead of having left padding it should be left margin? The padding makes it scroll in an unexpected area.

Edit 3: Went ahead and changed padding to margin on that to prevent weird scrolling.

**Comment by BennyHinrichs** [comment]
A related question: should the `.tsd-page-toolbar` be `position:fixed`? I personally like the option of always being able to search if I'm scrolled far down in a page.

**Comment by Gerrit0** [comment]
I think fixing the toolbar isn't a bad idea at all, but there's no reason to hold up this PR for that.

With the changes you've made this looks perfect! Thanks! Sorry for the delay here, its been a busy few weeks.

**Pull request merged**
