### PR TITLE
Search improvements - match in middle of word and fuzzy match

### PR DESCRIPTION
**Pull request by tomratcliffe**
* Updates to Lunr 2.3.2 - this should come from npm, but I didn't want to change the project structure/build process in this PR as that'd be too much in one go.
* Then uses wildcard searching so matching in the middle of terms should now work, e.g.
    * `est` will match `testing`
* Falls back to doing a fuzzy match if a wildcard match couldn't be found

Fixes:
* https://github.com/TypeStrong/typedoc/issues/803 (assuming I've understood that issue correctly)
* https://github.com/TypeStrong/typedoc/issues/649

Might help:
* https://github.com/TypeStrong/typedoc/issues/739

### CODE REVIEW

**Comment by tomratcliffe** [comment]
@aciccarello Any thoughts on this? Thanks!

**Comment by Roaders** [comment]
Is there any reason that this PR hasn't been merged? My team would like search to work from the middle of a name as well.

**Comment by tomratcliffe** [comment]
Hey @aciccarello, have you had a chance to look at this? Cheers

**Review by aciccarello — APPROVED** [review]
Sorry for the delay. Looks great! I'd like to check this locally before I merge.

**Pull request merged**
